---
title: "Stats102A, Summer 2023 - Homework 3"
author: "Luke Villanueva - 206039397"
date: "`r format(Sys.Date(), '%D')`"
output:
  pdf_document:
  extra_dependencies: ["amsmath"]
---

```{r include=F}
library(dplyr)
library(stringr)
library(tidyr)
source("206039397_stats102a_hw3.R")
```

# 1. Cook's relational data

```{r}
food <- read.csv("food_item.csv")
ingredient <- read.csv("ingredient.csv")
recipe <- read.csv("recipe.csv")
stock <- read.csv("stock.csv")
```

## a.

```{r}
ingredient %>% filter(recipe == "Beef Burger") %>% pull(food_item)
```

## b.

```{r}
ingredient %>% filter(str_detect(toupper(food_item),"TOMATO|BREAD"))
```

## c.

```{r}
food %>% filter(type == "Meat") %>% rename(food_item = item) %>% inner_join(stock, by = "food_item") %>% filter(shop %in% c("MyMart","Coco Mart")) %>% select(-3)
```

## d.

```{r}
res <- food %>% filter(type == "Wheat product") %>% rename(food_item = item) %>% inner_join(ingredient, by = "food_item") %>% select(recipe) %>% left_join(ingredient, by = "recipe") %>% rename(item = food_item)

# change tomato
res$item[11] <- "Tomato"

res %>% left_join(food, by = "item") %>% group_by(recipe) %>% summarise(Total_Calories = sum(calories))
```


# 2. Regular Expression Exercises

## 1.

### a.

```{r}
pat_1_a(names$names)
```

### b.

```{r}
pat_1_b(names$names)
```

### c.

```{r}
pat_1_c(names$names)
```

## 2. 

### a.

```{r}
pat_2_a(cards$cards)
```

### b.

```{r}
pat_2_b(cards$cards)
```

## 3.

### a.

```{r}
pat_3_a(passwords$passwords)
```

### b.

```{r}
pat_3_b(passwords$passwords)
```

## 4.

### a.

```{r}
pat_4_a(wordlists$Ranges$x, wordlists$Ranges$y)
```

### b.

```{r}
pat_4_b(wordlists$Backrefs$x, wordlists$Backrefs$y)
```

### c.

```{r}
pat_4_c(wordlists$Anchors$x, wordlists$Anchors$y)
```

