---
title: "Stats 20, W23 -- Homework 6"
author: "Luke Villanueva -- 206039397"
date: "`r format(Sys.Date(), '%D')`"
output:
  html_document:
    toc: yes            # creates table of contents
    toc_depth: 4        # toc will include headers <= ####
    toc_float: yes      # toc always on left of page
    code_folding: show  # allows hiding of code
---

# Question 1

## a.

```{r}

# inputs in single character format or in multiple character format
reading_ease <- function(x)
{
  
  # null check
  if(length(x) == 0)
  {stop("invalid input")}
  
  # regardless of char vec length, parse through each elem and split elem into strings based on sentences
  x <- unlist(strsplit(x, split = "[.!?:;]"))
  
  # calculate total sentences
  total_sentences <- length(x)
  
  # calculate total words: split words by spaces
  words <- unlist(strsplit(x, split = " "))
  # keep nonzero words
  words <- words[nchar(words) > 0]
  # calc total words
  total_words <- length(words)

  # calculate total syllables
  # short word rule: if word is 3 letters or less, count it as a syllable
  
  total_syllables <- 0
  for(word in words)
  {
  
    # split word into letters
    word_letters <- unlist(strsplit(word, split = ""))
    
    # short words
    if(length(word_letters) <= 3)
    {
      total_syllables <- total_syllables + 1
    }
    # check ending is in list
    # get word, get tail, go 2 in, check if es or ed
    else
    {
      
      # remove special endings
      word_tail <- tail(word_letters, n = 2)
      
      if (all(word_tail == c("e","s")) | all(word_tail == c("e","d")) | (word_tail[2] == "e" & word_tail[1] != "l")) 
      {
        if (word_tail[2] == "e") 
        {
          # remove e
          word_letters <- word_letters[-length(word_letters)]
        } 
        else 
        {
          word_letters <- head(word_letters, n = -2)
        }
      } 
      # if passes over, not special ending

      # is vowel check
      word_vowels <- word_letters %in% c("a","e","i","o","u","y")
      
      # increment syllable counter
      total_syllables <- total_syllables + sum(word_vowels) - sum(diff(which(word_vowels)) == 1)
      
    }

  }
  
  # output formula
  206.835 - (1.015 * (total_words / total_sentences)) - (84.6 * (total_syllables / total_words))

}


```

## b.

```{r}
waffles_vec <- c("We need to remember what's important in life: friends, waffles, work.", "Or waffles, friends, work.", "Doesn't matter, but work is third.")
reading_ease(waffles_vec)
```

# Question 2

```{r}

my_nchar <- function(x)
{
  
  # output is num vec
  res <- numeric(0)
  
  # x is char vec, so calculate char len for each elem
  for(elem in x)
  {
    res <- c(res,length(unlist(strsplit(elem, split = ""))))
  }
  
  #output
  res
  
}

my_nchar(c("hello","world"))

```

# Question 3

```{r}

my_strrep <- function(x, times)
{
  
  # output
  res <- ""
  
  for(i in seq_len(times))
  {
    res <- paste(res,x, sep = "")
  }
  
  res
  
}

my_strrep(c("hi","bye"),10)

```

# Question 4

```{r}

`%is_in%` <- function(x, table)
{
  
  # output
  res <- FALSE
  
  # for all elems in table, if x is equal, then return true
  table_vec <- unlist(as.list(table))
  for(elem in table_vec)
  {
    if(x == elem)
    {
      res <- TRUE
    }
  }
  
  # output
  res
  
}

```

# Question 5

```{r}

gregexpr("hello","iamhello")

my_gregexpr <- function(pattern, text)
{
  # for each element in text, parse to find pattern
  res <- list()

  for(i_txt in seq_along(text))
  { 
    # result
    index_text <- -1
    length_pattern <- -1
    type <- "chars"
    bool <- TRUE
    
    # bool for found
    index_found <- FALSE
    
    # separate characters in txt
    para <- unlist(strsplit(as.character(text[i_txt]), split = ""))
   
    # if found, return starting index, return length of string pattern
    # initial for loop to find starting elem
    for(i in seq_along(para))
    {
      # pattern split
      pat <- unlist(strsplit(as.character(pattern), split = ""))
      
      # if parse equals first index of pattern, check rest
      if(para[i] == pat[1])
      {
        # if length of para - i is less than pattern length, don't subset
        if((length(para) - i + 1) >= length(pat))
        {
          # theres room to subset
          sbset <- para[i:(i+length(pat)-1)]
          
          # if subset equals pattern, add index to res
          if(all(sbset == pat))
          {
            # if index not found, empty out index_text
            if(index_found == FALSE)
            {
              index_found <- TRUE
              length_pattern <- length(pat)
              index_text <- NULL
            }
            
            # concat index_text with index
            index_text <- c(index_text,i)
            
          }
        }
      }
      
    }

    # add list to res
    res[[i]] <- c(index_text, length_pattern, type, bool)
    
  }
  
  # output
  res
  
}

my_gregexpr(21,c(4322121,435985098121))

```