---
title: "Stats 20, W23 -- Homework 7"
author: "Luke Villanueva -- 206039397"
date: "`r format(Sys.Date(), '%D')`"
output:
  html_document:
    toc: yes            # creates table of contents
    toc_depth: 4        # toc will include headers <= ####
    toc_float: yes      # toc always on left of page
    code_folding: show  # allows hiding of code
---

# Question 1

## a. 

```{r}

births <- read.csv("births.csv", header = TRUE, stringsAsFactors = TRUE)

births[1:10,]

```

## b.

```{r}

with(births, length(Habit[Habit != "NonSmoker" & Habit != "Smoker"]))

with(births, attributes(Habit))

```

There are 6 observations. The category is called "".

## c.

```{r}

barplot(table(births$Habit), col = c("white","green", "red"))

```

## d.

```{r}
# get row indices based on habits not == ""
# subset entire data frame to known Habits
# use drop levels to drop unused factors in Habit

known_habit_births <- births[which(births$Habit == "Smoker" | births$Habit == "NonSmoker"),]

known_habit_births$Habit <- droplevels(known_habit_births$Habit)

# easier name
new_births <- known_habit_births

```

## e.

```{r}

boxplot(new_births$weight ~ new_births$Habit)

```

# Question 2

```{r}

h1 <- new_births$weight[new_births$Habit == "NonSmoker"]
h2 <- new_births$weight[new_births$Habit == "Smoker"]

# plot nonsmoker hist
hist(h1, freq = FALSE, density = 40, col = "green")

# plot smoker hist
hist(h2, freq = FALSE, density = 40, col = "red", add = TRUE)

# density of nonsmoker
lines(density(h1), col = "green")

abline(v = median(h1), col = "green", lwd = 2)
help(legend)
install.packages("dplyr")
library(plyr)
help(count)

```