---
title: "Stats 20, Winter 2023 - Homework 1"
author: "Luke Villanueva - 206039397"
date: "`r format(Sys.Date(), '%D')`"
output:
  html_document:
    toc: yes            # creates table of contents
    toc_depth: 4        # toc will include headers <= ####
    toc_float: yes      # toc always on left of page
    code_folding: show  # allows hiding of code
---

# Question 1
## a.
“**Sometimes you have to make the hardest climb to see the most beautiful sunrise.** I read that
once on an old lady’s decorative pillow, but it is really how I feel today. I’ve climbed a very weird and rocky
mountain, and it was a pain in the ass, and my legs are tired, and I’m starving. But *the sun is rising over a
sea of love and waffles and possibility.* So *I’m just gonna relax and take a deep breath and enjoy this view for
as long as I possibly can.*” – Leslie Knope (from Parks and Recreation)

<!--b.-->
| Homework | Midterm | Final Exam | Final Project |
|---------:|--------:|-----------:|--------------:|
| 18% | 30% | 40% | 12% |

<!--c.-->
- 2022
  - Fall
    - MATH115A - Linear Algebra
    - LBR STD 10 - Introduction to Labor and Workplace Studies
    - MATH42 - Introduction to Data-Driven Mathematical Modeling: Life, Universe, and Everything
  - Winter
     - MATH131A - Real Analysis
     - STATS20 - Introduction to Statistical Programming with R
     - STATS100A - Introduction to Probability
     
<!--d.-->
